# Generated by Django 5.1.7 on 2025-04-09 05:01

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Feeder', '0002_esp8266device'),
    ]

    operations = [
        migrations.AddField(
            model_name='esp8266device',
            name='device_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.CreateModel(
            name='DeviceCommand',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('command_type', models.CharField(choices=[('feed', 'Feed'), ('config', 'Configuration'), ('reboot', 'Reboot')], max_length=20)),
                ('parameters', models.JSONField(default=dict)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('sent', 'Sent'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commands', to='Feeder.esp8266device')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='FeedingHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('portion', models.PositiveIntegerField()),
                ('feed_type', models.CharField(choices=[('manual', 'Manual'), ('scheduled', 'Scheduled'), ('remote', 'Remote API')], max_length=20)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feeding_history', to='Feeder.esp8266device')),
            ],
            options={
                'verbose_name_plural': 'Feeding histories',
                'ordering': ['-timestamp'],
            },
        ),
    ]
